# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Yiran Han/Personal Homepage"
title_separator          : "-"
name                     : &name "Yiran Han"
description              : &description "PhD in Economics, University at Albany SUNY"
url                      : https://yiranhan.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "hamhammimi/yiranhan.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : # "Headshot.png"
  name             : "Yiran Han"
  pronouns         :  "she/her"  
  bio              : "PhD in Economics"
  location         : "New York"
  employer         : "University at Albany, SUNY"
  uri              : # URL
  email            : "yhan7@albany.edu" 

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=753EFhMAAAAJ"
  impactstory      : # URL
  orcid            : "https://orcid.org/0000-0003-0560-7744"
  semantic         : # URL
  pubmed           : 
  researchgate     : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : # "academicpages"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : # "bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # URL

